config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  
  resources :items do
    member do
      get :toggle #찜하기
      get :add
    end
  end
  resources :orders do
    member do
      delete :delete_line_item
    end
  end

  resources :user_items
  resources :comments

  root "items#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  def self.generate_categories
    %w(식품/생활
    패션/뷰티
    가전/디지털
    여행/레저).each_with_index do |category_title, index|
      Category.create(title: category_title, position: index)
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  paginates_per 5
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
	mount_uploader :image, ImageUploader # 이미지 첨부를 위해 이 부분 추가

  belongs_to :user, optional: true
  belongs_to :category, optional: true

  has_many :line_items, dependent: :nullify
  # 상품이 삭제되도 주문 항목은 삭제되면 안됨
  has_many :user_items, dependent: :destroy
  has_many :users, through: :user_items
  has_many :comments, dependent: :destroy
  # 찜하기는 상품이 삭제되면 삭제되어도 될 듯 

  def self.generate_items
    %w(아이폰 안드로이드 아이패드 맥북 시계 애플와치 갤럭시기어).each do |title|
      category = Category.first
      Item.create(title: title, price: 100000, category: category, image: Item.first.image, user: User.first, description:"상세한 설명이 있습니다")
    end
  end
end
 

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :item, optional: true

  # 상품이 삭제되어도 기존에 주문한 주문 항목은 남아있어야 하므로 optional로 정의하고
  # item 쪽에서 has_many 할 때는 destroy 대신 nullify

  # line_item이 변경될 때마다 주문의 총 가격 변경하기
  # line_item 본인을 변경할 때는 after_save 후 update 하지말고 (재귀함수처럼 계속 호출됨)
  # before_save gkrh update 대신 = 로 할당만 해서 save 할 때 한 번에 저장되도록 처리함
 
  # line_item 본인이 아니라 order를 수정하는 것이므로 after_save 후 order.update를 해도 될듯

  after_save :set_order_total

  def set_order_total
    puts "set_order_total"
    order.update(total: order.line_items.sum("amount * price"))
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  enum status: [:cart, :paid, :canceled]

  has_many :line_items, dependent: :nullify
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_items, dependent: :destroy # 찜하기는 회원이 삭제되거나 탈퇴하면 지워져도 됨
  has_many :items, through: :user_items ,dependent: :nullify# 등록된 상품을 등록한 회원이 삭제되더라도 주문이나 리뷰 등 
  #  다른 데이터와 많이 엮여 있어서 삭제하지 않고 foreign_key만 null로 갱신
    
  has_many :orders

  def has_item? item
    user_items.where(item: item).present?
  end
  
end

app/models/user_item.rb
class UserItem < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def get_cart
    # 현재 로그인한 유저가 가진 주문 중 cart 상태의 주문을 하나 찾아서 가져오거나
    # 없으면 하나 새로 생성함
    current_user.orders.cart.first_or_create
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create comment_params
    @item = Item.find_by(id: @comment.item_id)
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @comment.destroy
    
    @item = Item.find_by(id: @comment.item_id)
  end

  private 
  def comment_params
    params.require(:comment).permit(:content, :user_id, :item_id)
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show] # 찜하기는 로그인 해야지만 이용 가능
  before_action :load_object, only: %i[show toggle edit update destroy add test] # 상품 상세와 찜하기는 @item을 먼저 불러옴
  before_action :check_owner, only: %i[edit update destroy] # 수정/삭제는 상품 소유자만 할 수 있도록

  def index
    if params[:type] == 'selling'
      redirect_to root_path, notice: '로그인을 해야 합니다' unless current_user
      @items = current_user.items
    else
      @items = Item.all
      # 카테고리별 페이지
      if params[:category_id].present?
        @category = Category.find(params[:category_id])
        @items = @items.where(category_id: params[:category_id])
      end
    end
    if params[:q].present?
      @items = @items.ransack(title_or_description_cont: params[:q]).result(distinct: true)
    end
    @items = params[:order].blank? ? @items.order(created_at: :desc) : @items.order(params[:order])
    @items = @items.page(params[:page]).per(20)
  end

  def toggle
    if user_item = current_user.user_items.where(item: @item).first
      # 이미 찜한 상태라면 찜을 제거
      user_item.destroy
      flash[:notice] = '찜을 제거하였습니다.'
    else
      # 찜한 적이 없으면 찜하기
      current_user.user_items.where(item: @item).create
      flash[:notice] = '찜하였습니다.'
    end
    redirect_to @item
  end

  def add
    # edit은 판매자가 상품 편집을 하는데 사용해야 하므로
    @order = get_cart
    line_item = @order.line_items.where(item: @item).first_or_create(price: @item.price)
    line_item.increment!(:amount)
    line_item.set_order_total
    redirect_to new_order_path, notice: '장바구니에 상품을 담았습니다.'
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.create(item_params)
    @item.update(user: current_user)
    redirect_to items_path(type: :selling), notice: '상품을 등록했습니다'
  end

  def edit
  end

  def update
    @item.update(item_params)
    redirect_to items_path(type: :selling), notice: '상품을 등록했습니다'
  end

  def show
  end

  def destroy
    @item.destroy
    redirect_back fallback_location: root_path
  end

  private

  def load_object
    @item = Item.find params[:id]
  end

  def item_params
    params.require(:item).permit(:title, :price, :description, :image, :category_id)
  end

  def check_owner
    redirect_to root_path, notice: '권한이 없습니다' unless @item.user == current_user
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_object, :check_owner, only: [:edit, :show, :update, :destroy, :delete_line_item]
  # 다른 사람도 주문 아이디만 알면 접근이 가능한 상태이므로 내 주문은 나만 볼 수 있도록 권한 체크할 필요

  def new
    @order = get_cart
  end

  def edit
  end
  
  def update
    @order.paid!
    @order.update(paid_at: Time.new)
    redirect_to @order
  end

  def index
    @orders = current_user.orders.order(:paid_at).page(params[:page]).per(10)
  end
  
  def delete_line_item
    puts params
    @order.line_items.find(params[:line_item_id]).destroy
    redirect_to new_order_path
  end
  
  private
  
  def load_object
    @order = Order.find(params[:id])
  end
  
  def check_owner
    redirect_to root_path, notice: "권한이 없습니다" unless @order.user == current_user
  end

end

app/controllers/user_items_controller.rb
class UserItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_items = current_user.user_items.page(params[:page]).per(10)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/user_items_helper.rb
module UserItemsHelper
end

app/views/comments/_comment.html.erb
<% comment||= nil %>
<% if comment %>
 <div class="list-group-item list-group-item-aciton" id="comment-<%= comment.id %>">
  <div class="row">
    <div class="col-md-2"> <%= comment.user&.email %> </div>
    <div class="col-md-8"> <%= comment.content %> </div>
    <div class="col-md-1"> <p style="font-size:0.8em"><%= time_ago_in_words(comment.created_at) %></p> </div>
    <div class="col-md-1 float-right">
      <% if current_user == comment.user %>
        <%=link_to "삭제", comment_path(comment), class: "text-danger float-right", method: :delete, remote: true%>
      <% end %>
    </div>
  </div>
 </div>
<% end %>

app/views/comments/_comments.html.erb
<% comments||= nil%>

<div class="list-group">
  <% if comments.present? %>
    <% comments.each do |comment| %>
      <%= render 'comments/comment', comment: comment %>
    <% end %>
  <% else %>
    <div class="list-group-item list-group-item-action" >
      <h5>댓글이 없습니다.</h5>
    </div>
  <% end %>
  <%= paginate comments, window: 2 %>

</div>

app/views/comments/_form.html.erb
<% comment ||= nil %>
<% item ||= nil %>
<% user ||= nil %>
<% if comment && item && user %>
  <h4 class="mt-5 test">
    <%= comment.new_record? ? "댓글 작성" : "댓글 수정" %>
  </h4>
  <div>
    <%= form_for comment, remote:true do |f| %>
      <%= f.text_area :content, class: "form-control", :required => 'required' %>
      <div class="row p-3 justify-content-end">
        <%= f.submit (comment.new_record? ? "댓글 작성" : "댓글 수정"), class:"btn bg-primary text-white" %>
      </div>
      <%= f.hidden_field :item_id, value: item.id %>
      <%= f.hidden_field :user_id, value: user.id %>
    <% end %>
  </div>
<% end %>

app/views/comments/create.js.erb
$("#comment_content").val("")
<!-- 
$(".list-group").prepend("<%= j render 'comments/comment', comment: @comment %>")
-->
$(".list-group").replaceWith("<%= j render 'comments/comments', comments: @item.comments.order(created_at: :desc) %>"); 

alert("댓글이 생성 되었습니다.")

app/views/comments/destroy.js.erb
$("#comment-<%= @comment.id %>").remove()
$(".list-group").replaceWith("<%= j render 'comments/comments', comments: @item.comments.order(created_at: :desc) %>"); 
alert("댓글이 삭제 되었습니다.")

app/views/items/_form.html.erb
<div class="container my-5">
  <div class="row">
    <div class="card col-md-6 offset-md-3 p-5 mt-2">
      <%= form_for @item do |f|%>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :price %>
          <%= f.text_field :price, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :image, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :category_id %>
          <%= f.select :category_id, options_for_select(Category.order(:position).map {|category| [category.title, category.id]}), {}, class:"form-control" %>
        </div>

        <%= f.submit "상품 등록", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<%= render "form" %>

app/views/items/index.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-12 mb-2">
      <% if params[:type] == "selling" %>
        <h2>나의 상품</h2>
      <% elsif @category %>
        <h2><%= @category.title %></h2>
      <% end%>
      <hr> 
      <%= form_tag request.parameters, method: :get do  %>
        <div class="form-inline float-left">
          <%= text_field_tag :q, params[:q], class:"form-control mr-1" %>
          <%= submit_tag "검색", class:"btn btn-primary mr-1" %>
        </div>  

        <div class="float-right">
            <div class="btn-group">
              <%= link_to "가격순", request.parameters.merge(order: :price), class:"btn btn-#{params[:order].present? ? "secondary" : "outline-secondary"}"%>
              <%= link_to "등록순", request.parameters.merge(order: nil), class:"btn btn-#{params[:order].blank? ? "secondary" : "outline-secondary"}"%>
            </div>
            <%= link_to "상품 등록", new_item_path, class:"btn btn-primary" %>
          </div>
      <% end %>
    </div>

    <% @items.each do |item| %>
      <div class="col-md-3 mb-4">
        <div class="card">
          <img src="<%= item.image.url(:thumb) if item.image?%>" class="card-img-top" alt="...">
          <div class="card-body">
            <h4 class="card-title"> <%= truncate(item.title,length: 10) %> </h4>
            <div class="card-subtitle">판매자: <%= item.user&.email%></div>
            <p class="card-text"> <%= truncate(item.description,length:20) %> </p>
            <p class="text-muted"> <%= number_with_delimiter item.price %>원</p>
          </div>
          <div class="card-footer form align-middle">
            <%= link_to "자세히 보기", item, class:"btn btn-primary btn-sm align-middle" %>
            <% if item.user == current_user %>
              <%= link_to "수정", edit_item_path(item), class:"btn btn-secondary btn-sm"%>
              <%= link_to "삭제", item, method: :delete, data: {confirm: "정말로 삭제하시겠습니까?"}, class:"btn btn-danger btn-sm"%>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= paginate @items %>
</div>

app/views/items/new.html.erb
<%= render "form" %>

app/views/items/show.html.erb
<style>
  .max-small {
    width: 100%;
    height: 100%;
    max-width: 300px;
    max-height: 300px;
  }
</style>

<div class="container my-5">
  <div class="row">
    <div class="col-md-4">
      <%= image_tag @item.image.url, class:"img-thumbnail img-fluid max-small"%>
    </div>
    <div class="col-md-8">
      <h4><%= @item.title %></h4>
      <p><%= number_with_delimiter @item.price %>원</p>
      <%= link_to current_user&.has_item?(@item) ? "찜 취소하기" : "찜하기", toggle_item_path(@item),class:"btn btn-primary"%>  
      <%= link_to "장바구니 담기", add_item_path(@item), class:"btn btn-secondary"%>
      <!-- edit 액션 대신 add 또는 orders 컨트롤러의 액션 등을 사용할 수 있으나 items#edit 액션을 사용할 일이 없으므로 대신 사용-->
    
      <div class="mt-3">
        <%= simple_format @item.description%>
      </div>
    </div>
  </div>
  <hr>
  <% if current_user %>
    <%= render "comments/form", comment: Comment.new, item: @item, user: current_user %>
  <% end %>
  <hr>
  <%= render 'comments/comments', comments: @item.comments.order(created_at: :desc).page(params[:comments_page]) %> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Market</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  
  <body>
    <% if notice %>
      <div class="alert alert-success">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end%>
    <%= render "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/orders/edit.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col">
      <div class="card p-5">
        <h2>주문 정보 입력</h2>
        <hr>

        <%= form_for @order do |f| %>
          <div class="form-group">
            <%= f.label :zipcode %>
            <%= f.text_field :zipcode , class:"form-control"%>
          </div>
          <div class="form-group">
            <%= f.label :address1 %>
            <%= f.text_field :address1 , class:"form-control"%>
          </div>
          <div class="form-group">
            <%= f.label :address2 %>
            <%= f.text_field :address2 , class:"form-control"%>
          </div>
          <%= f.submit "결제하기", class: "btn btn-primary" %>

          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col">
      <% @orders.each do |order| %>
        <div class="card p-3 mb-3">
          <% order.line_items.each do |line_item| %>
            <% if item = line_item.item %>
              <%= line_item.item.title %> (<%= number_with_delimiter (line_item.price )%>원 * <%= line_item.amount %>개)  
            <% else%>
              삭제된 상품 입니다.
            <% end %>
          <% end %>
          <hr>
          <%= number_with_delimiter order.total %>원
        </div>
      <% end %>
      <%= paginate @orders %>
    </div>
  </div>
</div>

app/views/orders/new.html.erb
<style>
  .max-small {
    width: auto;
    height: auto;
    max-width: 100px;
    max-height: 100px;
  }
</style>

<div class="container my-5">
  <div class="row">
    <div class="col-12 mb-2">
      <h2>장바구니</h2>
      <hr>
      <% if @order.line_items.blank? %>
        <div class="card p-3 text-center">
          장바구니가 비어있습니다
        </div>
      <% else %>
        <table class="table container p-2 border">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">상품명</th>
              <th scope="col">수량</th>
              <th scope="col">가격</th>
              <th scope="col">Handle</th>
            </tr>
          </thead>
          <tbody>
            <% @order.line_items.each do |line_item| %>
              <tr>
                <td><img src="<%= line_item.item.image.url(:thumb) if line_item.item.image? %>" class="col rounded max-small"
                alt="..."></td>
                <td><%= line_item.item.title %></td>
                <td><%= line_item.amount %>개</td>
                <td><%= line_item.price %>원</td>
                <td><%= link_to "삭제", delete_line_item_order_path(@order, :line_item_id => line_item.id),  method: :delete, data: {confirm: "정말로 삭제하시겠습니까?"}, class:"btn btn-danger btn-sm"%></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        
      </div>

      <p>
        총금액: <%= number_with_delimiter @order.total %>원
      </p>
      <%= link_to "주문하기", edit_order_path(@order), class: "btn btn-primary"%>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col">
      <div class="card p-5">
        <%= number_with_delimiter @order.total %>원
      </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <a class="navbar-brand" href="/">MARKET</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

  <div class="collapse navbar-collapse justify-content-between" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <% Category.order(:position).each do |category| %>
        <li class="nav-item">
          <a class="nav-link <%= params[:category_id].to_i == category.id ? "active" : "" %>"
            href="<%= items_path(category_id: category.id) %>"> <%= category.title %> </a>
        </li>
      <% end %>
    </ul>

    <ul class="navbar-nav">
      <% if current_user %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            마이페이지
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="<%= new_order_path %>">장바구니</a>
            <a class="dropdown-item" href="<%= user_items_path %>">찜한 상품</a>
            <a class="dropdown-item" href="<%= orders_path %>">내 주문</a>
            <a class="dropdown-item" href="<%= items_path(type: :selling) %>">내 상품</a>
            <a class="dropdown-item" href="<%= edit_user_registration_path %>">회원정보수정</a>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to  "로그아웃", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <a class="nav-link active" href="<%= new_user_session_path %>">로그인</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="<%= new_user_registration_path %>">회원가입</a>
        </li>
      <% end %>
    </ul>
  </div>
  </div>
</nav>

app/views/user_items/index.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-12 mb-2">
      <h2>찜한 상품</h2>
      <hr>  
    </div>

    <% @user_items.each do |user_item| %>
      <% if item = user_item.item%>
        <div class="col-md-3 mb-4">
          <div class="card">
            <img src="<%= item.image.url(:thumb) if item.image?%>"  class="card-img-top" alt="...">
            <div class="card-body">
              <h4 class="card-title"> <%= item.title %> </h4>
              <div class="card-subtitle">판매자: <%= item.user&.email%></div>
              <p class="card-text"> <%= item.description %> </p>

              <%= link_to "자세히 보기", item, class:"btn btn-primary btn-sm" %>
              <% if item.user == current_user %>
                <%= link_to "수정", edit_item_path(item), class:"btn btn-secondary  btn-sm"%>
                <%= link_to "삭제", item, method: :delete, data: {corfirm: "정말로  삭제하시겠습니까?"}, class:"btn btn-danger btn-sm"%>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= paginate @user_items %>
</div>